# -*- coding: utf-8 -*-
"""Exercico 1 integral.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MT73xuDTuVDBW6xat29lgnwv5s15S8FQ
"""

def trapezio(func,a,b,N):
  x = np.linspace(a,b,N+1)
  h = (b-a)/N
  Soma = (func(a) + func(b))/2.0
  for xx in x[1:N]:
    Soma = Soma + func(xx)
  return Soma *h


def poli(x):
    return x**5+3*x+5

a=0
b=1


real = (1/6) * (b**6 - a**6) + (3/2) * (b**2 - a**2) + 5 * (b - a)
Ns=[10,100,1000]
for N in Ns:
  integral = trapezio(poli, a, b, N)
  erro = abs(integral - real)

print(integral)
print(erro)